server {
	root ./www/site1
	listen 127.0.0.1
	port 9001
	server_name Principal
	error_page 404 ./www/site1/errors/404.html
	error_page 405 ./www/site1/errors/405.html
	max_body_size 50000000
	index acceuil.html

	route /redirect {
		redirect 301 https://www.google.com
		methods GET
	}

	route /api {
		root ./www/site1/api
		methods GET POST
		directory_listing on
		cgi on
		cgi_extension .php
		cgi_path /opt/homebrew/bin/php
	}

	route /upload {
		root ./www/site1/upload
		methods GET POST DELETE
		upload on
		upload_path ./www/upload
	}


	route /hello { 
		root ./www/site1/cgi-bin/hello.php
		methods GET POST
		cgi on
		cgi_extension .php
		cgi_path /opt/homebrew/bin/php
	}

	route /list_files { 
		root ./www/site1/cgi-bin/list_files.php
		methods GET POST
		cgi on
		cgi_extension .php
		cgi_path /opt/homebrew/bin/php
	}

	route /login {
		root ./www/site1/cgi/login.py
		methods POST GET
		cgi on
		cgi_extension .py
		cgi_path /opt/homebrew/bin/python3
	}

	route /search {
		root ./www/site1/cgi/search.py
		methods POST GET
		cgi on
		cgi_extension .py
		cgi_path /opt/homebrew/bin/python3
	}

	route /get_logs { 
		root ./www/site1/cgi-bin/get_logs.php
		methods GET POST
		cgi on
		cgi_extension .php
		cgi_path /opt/homebrew/bin/php
	}

	route /infinite { 
		root ./www/site1/cgi-bin/infinite.php
		methods GET POST
		cgi on
		cgi_extension .php
		cgi_path /opt/homebrew/bin/php
	}

	route /sysinfo {
		root ./www/site1/cgi-bin/sysinfo.py
		methods GET POST
		cgi on
		cgi_extension .py
		cgi_path /opt/homebrew/bin/python3
	}

	route /list_env {
		root ./www/site1/cgi-bin/list_env.sh
		methods GET POST
		cgi on
		cgi_extension .sh
		cgi_path /bin/bash
	}
}