#!/usr/bin/env python3
import os

method = os.environ.get("REQUEST_METHOD", "")
query = os.environ.get("QUERY_STRING", "")
path_info = os.environ.get("PATH_INFO", "")
server = os.environ.get("SERVER_NAME", "")
port = os.environ.get("SERVER_PORT", "")
contentType = os.environ.get("CONTENT_TYPE", "")
contentLenght = os.environ.get("CONTENT_LENGHT", "")
scrypt = os.environ.get("SCRIPT_NAME", "")
protocol = os.environ.get("SERVER_PROTOCOL", "")
sotware = os.environ.get("SERVER_SOFTWARE", "")
interface = os.environ.get("GATEWAY_INTERFACE", "")


print("Content-Type: text/html")
print()
print("<html><body>")
print("<h1>Résultat de recherche</h1>")
print(f"<p>method : {method}</p>")
print(f"<p>Tu as cherché (query) : {query}</p>")
print(f"<p>path_info : {path_info}</p>")
print(f"<p>server : {server}</p>")
print(f"<p>port : {port}</p>")
print(f"<p>content type : {contentType}</p>")
print(f"<p>content lenght: {contentLenght}</p>")
print(f"<p>scrypt : {scrypt}</p>")
print(f"<p>protocol : {protocol}</p>")
print(f"<p>sotware : {sotware}</p>")
print(f"<p>interface : {interface}</p>")
print("</body></html>")
