# TODO: si index et route / pas la on fait quoi?? et si index pas /

server {
	root ./www
	listen 127.0.0.1
	port 2224
	server_name Principal
	error_page 404 ./errors/404.html
	error_page 405 ./errors/405.html
	max_body_size 5000000
	index acceuil.html

	route / {
		root ./www
		directory_listing on
		methods GET POST DELETE
	}

	route /redirect {
		redirect 301 https://www.google.com
		methods GET
	}

	route /api {
		root ./www/api
		methods GET POST
		directory_listing on
		cgi on
		cgi_path /usr/bin/php
	}

	route /upload {
		root ./www/upload
		methods GET POST DELETE
		upload on
		upload_path ./www/upload
	}


	route /hello { 
		root ./www/cgi-bin/hello.php
		methods GET POST
		cgi on
		cgi_extension .php
	}

	route /list_files { 
		root ./www/cgi-bin/list_files.php
		methods GET POST
		cgi on
		cgi_extension .php
	}

	route /login {
		root ./cgi/login.py
		methods POST GET
		cgi_extension .py
	}
	route /get_logs { 
		root ./www/cgi-bin/get_logs.php
		methods GET POST
		cgi on
		cgi_extension .php
	}

	route /infinite { 
		root ./www/cgi-bin/infinite.php
		methods GET POST
		cgi on
		cgi_extension .php
	}

	route /sysinfo {
		root ./www/cgi-bin/sysinfo.py
		methods GET POST
		cgi on
		cgi_extension .py
	}

	route /list_env {
		root ./www/cgi-bin/list_env.sh
		methods GET POST
		cgi on
		cgi_extension .sh
	}
}

server {
	root ./www
	listen 127.0.0.222
	port 2224
	server_name t2
	error_page 404 ./errors/404.html
	error_page 405 ./errors/405.html
	max_body_size 50000
	index acceuil.html

	route / {
		root ./www
		directory_listing on
		methods GET POST DELETE
	}

	route /api {
		root ./www/api
		methods GET POST
	}

	route /upload {
		root ./www/upload
		methods GET POST DELETE
		upload on
		upload_path ./www/upload
	}

}
