server {
	root ./www
	listen 127.0.0.1
	port 2224
	server_name raph_test
	error_page 404 ./errors/404.html
	autoindex on

	route / {
		root ./www
		methods GET POST DELETE
	}

	route /upload {
		root ./www/upload
		methods GET POST DELETE
		upload on
		upload_path ./www/upload
	}

	route /api {
		root ./www
		methods GET POST
	}

	route /hello { 
		root ./www/cgi-bin/hello.php
		methods GET POST
		cgi on
		cgi_extension .php
		cgi_path /opt/homebrew/bin/php
	}

	route /list_files { 
		root ./www/cgi-bin/list_files.php
		methods GET POST
		cgi on
		cgi_extension .php
		cgi_path /opt/homebrew/bin/php
	}

	route /get_logs { 
		root ./www/cgi-bin/get_logs.php
		methods GET POST
		cgi on
		cgi_extension .php
		cgi_path /opt/homebrew/bin/php
	}

	route /infinite { 
		root ./www/cgi-bin/infinite.php
		methods GET POST
		cgi on
		cgi_extension .php
		cgi_path /opt/homebrew/bin/php
	}

	route /sysinfo {
		root ./www/cgi-bin/sysinfo.py
		methods GET POST
		cgi on
		cgi_extension .py
		cgi_path /usr/bin/python3
	}

	route /list_env {
		root ./www/cgi-bin/list_env.sh
		methods GET POST
		cgi on
		cgi_extension .sh
		cgi_path /bin/bash
	}

	max_body_size 5000000
}
