#!/bin/bash
# A detailed bash CGI script to output environment variables and system state

# Required CGI Headers
echo -ne "Content-Type: text/html\r\n"
echo -ne "X-Powered-By: Webserv-Bash\r\n"
echo -ne "\r\n"

# Only output HTML from here down
cat << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bash Environment Variables</title>
    <style>
        :root { --bg: #1e1e1e; --color: #d4d4d4; --acc: #569cd6; --border: #333; }
        body { font-family: "Consolas", "Courier New", monospace; background: var(--bg); color: var(--color); margin: 0; padding: 20px; line-height: 1.6; }
        .container { max-width: 900px; margin: 0 auto; }
        .header { border-bottom: 2px solid var(--acc); padding-bottom: 10px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: flex-end; }
        h1 { margin: 0; color: var(--acc); font-size: 1.8em; }
        .subtitle { font-size: 0.9em; opacity: 0.7; }
        .grid-info { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 30px; background: #252526; padding: 15px; border-radius: 5px; border: 1px solid var(--border); }
        table { width: 100%; border-collapse: collapse; background: #252526; border-radius: 5px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.3); }
        th { background: #2d2d30; text-align: left; padding: 12px; color: var(--acc); font-weight: normal; border-bottom: 1px solid var(--border); }
        td { padding: 10px 12px; border-bottom: 1px solid var(--border); word-break: break-all; }
        tr:last-child td { border-bottom: none; }
        tr:hover { background: #2a2d2e; }
        .key { color: #9cdcfe; font-weight: bold; width: 30%; }
        .value { color: #ce9178; }
        .value.empty { color: #808080; font-style: italic; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div>
                <h1>Terminal Environment</h1>
                <div class="subtitle">Generated by Bash CGI script</div>
            </div>
EOF

# Inject Bash evaluated values into HTML
echo "<div>Date: $(date '+%Y-%m-%d %H:%M:%S')</div>"
echo "</div>"

echo '<div class="grid-info">'
echo "<div><strong>Bash Version:</strong> ${BASH_VERSION}</div>"
echo "<div><strong>User:</strong> $(whoami)</div>"
echo "<div><strong>Uptime:</strong> $(uptime | awk -F'( |,|:)+' '{print $6,$7}')</div>"
echo "<div><strong>Current Dir:</strong> $(pwd)</div>"
echo '</div>'

echo '<table>'
echo '<tr><th>Variable Name</th><th>Value</th></tr>'

# Parse 'env' and print table rows
env | sort | while IFS='=' read -r key value; do
    if [ -z "$value" ]; then
        echo "<tr><td class=\"key\">${key}</td><td class=\"value empty\">[empty]</td></tr>"
    else
        echo "<tr><td class=\"key\">${key}</td><td class=\"value\">${value}</td></tr>"
    fi
done

echo '</table>'

cat << 'EOF'
    </div>
</body>
</html>
EOF
