#!/usr/bin/env python3
import os
import platform
import subprocess
from datetime import datetime
from urllib.parse import parse_qs

# Parse QUERY_STRING
query_string = os.environ.get('QUERY_STRING', '')
params = parse_qs(query_string)

# Check if 'theme' parameter is present (e.g. ?theme=light)
theme = params.get('theme', ['dark'])[0].lower()
bg_color = "#ffffff" if theme == 'light' else "#0d1117"
text_color = "#24292f" if theme == 'light' else "#c9d1d9"
box_bg = "#f6f8fa" if theme == 'light' else "#161b22"
border_color = "#d0d7de" if theme == 'light' else "#30363d"
title_color = "#0969da" if theme == 'light' else "#58a6ff"

# Simuler l'usage CPU/RAM sans librairie externe en lisant les commandes système
try:
    if platform.system() == "Darwin": # macOS
        # CPU
        cpu_load = subprocess.check_output("top -l 1 | grep 'CPU usage' | awk '{print $3}'", shell=True).decode().strip()
        cpu_percent = cpu_load.replace("%", "") if cpu_load else "N/A"
        # RAM
        mem_wired = subprocess.check_output("vm_stat | grep 'wired down' | awk '{print $4}'", shell=True).decode().strip().replace(".", "")
        mem_percent = f"Approximated via vm_stat"
        mem_total = "See system tools"
    else: # Linux
        # CPU
        cpu_percent = subprocess.check_output("top -bn1 | grep 'Cpu(s)' | sed 's/.*, *\\([0-9.]*\\)%* id.*/\\1/' | awk '{print 100 - $1}'", shell=True).decode().strip()
        # RAM
        mem_output = subprocess.check_output("free -m | awk 'NR==2{printf \"%.2f%% of %.2f GB\", $3*100/$2, $2/1024 }'", shell=True).decode().strip()
        mem_percent = mem_output.split(" of ")[0]
        mem_total = mem_output.split(" of ")[1] if "of" in mem_output else "N/A"
except Exception:
    cpu_percent = "N/A"
    mem_percent = "N/A"
    mem_total = "N/A"

# Headers
print("Content-Type: text/html\r\n", end="")
print("X-Powered-By: Webserv-CGI\r\n", end="")
print("\r\n", end="") # End of headers

# Body HTML
html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>System Info CGI</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; background: {bg_color}; color: {text_color}; padding: 30px; transition: all 0.3s; }}
        .container {{ max-width: 800px; margin: 0 auto; }}
        .box {{ border: 1px solid {border_color}; background: {box_bg}; padding: 25px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
        h1 {{ color: {title_color}; margin-top: 0; display: flex; align-items: center; justify-content: space-between; }}
        .theme-btn {{ padding: 8px 15px; border-radius: 6px; text-decoration: none; font-size: 14px; background: {title_color}; color: white; border: none; font-weight: bold; cursor: pointer; }}
        h2 {{ border-bottom: 1px solid {border_color}; padding-bottom: 8px; margin-top: 30px; font-size: 1.2em; }}
        .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 15px; }}
        .stat-item {{ padding: 10px; background: rgba(128,128,128,0.1); border-radius: 6px; border-left: 4px solid {title_color}; }}
        .stat-label {{ font-size: 12px; text-transform: uppercase; opacity: 0.8; margin-bottom: 5px; }}
        .stat-value {{ font-size: 18px; font-weight: bold; }}
        .env-var {{ font-family: monospace; font-size: 13px; background: rgba(128,128,128,0.1); padding: 2px 6px; border-radius: 4px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="box">
            <h1>
                <span>🐍 Webserv System Info</span>
                <a href="?theme={'dark' if theme == 'light' else 'light'}" class="theme-btn">Switch to {'Dark' if theme == 'light' else 'Light'} Mode</a>
            </h1>
            <p>This page is dynamically generated by a <strong>Python CGI</strong> script demonstrating server info retrieval.</p>
            
            <h2>Hardware Details</h2>
            <div class="grid">
                <div class="stat-item"><div class="stat-label">OS</div><div class="stat-value">{platform.system()} {platform.release()}</div></div>
                <div class="stat-item"><div class="stat-label">Architecture</div><div class="stat-value">{platform.machine()}</div></div>
                <div class="stat-item"><div class="stat-label">CPU Usage</div><div class="stat-value">{cpu_percent}%</div></div>
                <div class="stat-item"><div class="stat-label">Memory Usage</div><div class="stat-value">{mem_percent}% of {mem_total}</div></div>
            </div>

            <h2>Software Environment</h2>
            <div class="grid">
                <div class="stat-item"><div class="stat-label">Python Version</div><div class="stat-value">{platform.python_version()}</div></div>
                <div class="stat-item"><div class="stat-label">Server Time</div><div class="stat-value">{datetime.now().strftime('%H:%M:%S')}</div></div>
                <div class="stat-item"><div class="stat-label">CGI Interface</div><div class="stat-value">{os.environ.get('GATEWAY_INTERFACE', 'Unknown')}</div></div>
                <div class="stat-item"><div class="stat-label">Server Software</div><div class="stat-value">{os.environ.get('SERVER_SOFTWARE', 'Webserv')}</div></div>
            </div>

            <h2>CGI Request Data</h2>
            <ul>
                <li><strong>Method:</strong> <span class="env-var">{os.environ.get('REQUEST_METHOD', 'N/A')}</span></li>
                <li><strong>Remote Address:</strong> <span class="env-var">{os.environ.get('REMOTE_ADDR', '127.0.0.1')}</span></li>
                <li><strong>Query String:</strong> <span class="env-var">{query_string if query_string else 'None'}</span></li>
            </ul>
        </div>
        
        <script>
            console.log("🚀 Welcome to Webserv Python CGI!");
            console.log("Current Theme:", "{theme}");
            console.log("Query String parsed:", {dict(params)});
        </script>
    </div>
</body>
</html>
"""

print(html)

